[build]
command = "npm ci && npm run build"
builder = "NIXPACKS"
watchPatterns = ["src/**", "public/**", "index.html", "package.json", "vite.config.ts"]

[deploy]
startCommand = "npm run preview"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 300

[environment]
NODE_ENV = "production"
NIXPACKS_BUILD_CMD = "npm ci && npm run build"
NIXPACKS_START_CMD = "npm run preview"
