
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './mock-types';

const SUPABASE_URL = "https://oqcicjjjicazrfgdgynl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xY2ljampqaWNhenJmZ2RneW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjk3NTUsImV4cCI6MjA1OTYwNTc1NX0.LShb5xBk_D8HCRhAkoHs2bwcvKt_RFxhiLHjNH5qXkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a new Supabase client with proper type definitions
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      storageKey: 'toti-supabase-auth'
    }
  }
);
