// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbnxjzdsvakuregllyhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdibnhqemRzdmFrdXJlZ2xseWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNjY2MDIsImV4cCI6MjA1Nzg0MjYwMn0.TK0v0y0Fd2EfLrD6kc6Rs-B-veC5_wYdytm-xSqUIt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);